### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by IrzaMushaffa** [ThingEngineer/PHP-MySQLi-Database-Class#993]
hello, i'm using this package and trying to make my website online, but when i tried to i got the error log saying :

[18-Jul-2022 10:44:52 UTC] PHP Warning:  mysqli::__construct(): (HY000/1044): Access denied for user 'webgispa_admin'@'localhost' to database 'webgispa_webgis-php' in /home/webgispa/public_html/vendor/thingengineer/mysqli-database-class/MysqliDb.php on line 323
[18-Jul-2022 10:44:52 UTC] PHP Fatal error:  Uncaught Exception: Connect Error 1044: Access denied for user 'webgispa_admin'@'localhost' to database 'webgispa_webgis-php' in /home/webgispa/public_html/vendor/thingengineer/mysqli-database-class/MysqliDb.php:326
Stack trace:
#0 /home/webgispa/public_html/vendor/thingengineer/mysqli-database-class/MysqliDb.php(415): MysqliDb->connect('default')
#1 /home/webgispa/public_html/vendor/thingengineer/mysqli-database-class/MysqliDb.php(1995): MysqliDb->mysqli()
#2 /home/webgispa/public_html/vendor/thingengineer/mysqli-database-class/MysqliDb.php(1601): MysqliDb->_prepareQuery()
#3 /home/webgispa/public_html/vendor/thingengineer/mysqli-database-class/MysqliDb.php(751): MysqliDb->_buildQuery(NULL)
#4 /home/webgispa/public_html/_halaman/js/leaflet-pointmarkerJs.php(77): MysqliDb->get('m_kecamatan')
#5 /home/webgispa/public_html/index.php(66): include('/home/webgispa/...')
#6 {main}
  thrown in /home/webgispa/public_html/vendor/thingengineer/mysqli-database-class/MysqliDb.php on line 326

does anyone have any idea whats going on? Thank you ....

**Comment by aanjos90** [comment]
Is the DB host correct on your settings? It says here: "Access denied for user 'webgispa_admin'@'localhost' to database 'webgispa_webgis-php'". It's probably a username, password and host issue, not with the library.
