### ISSUE TITLE
Not working with PHP 8.1.2

### ISSUE THREAD

**Issue by thistehneisen** [ThingEngineer/PHP-MySQLi-Database-Class#998]
```
PHP message: PHP Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/www/vhosts/[hidden]/httpdocs/vendor/thingengineer/mysqli-database-class/MysqliDb.php:1838\nStack trace:\n#0 /var/www/vhosts/[hidden]/httpdocs/vendor/thingengineer/mysqli-database-class/MysqliDb.php(1838): implode()\n#1 /var/www/vhosts/[hidden]/httpdocs/vendor/thingengineer/mysqli-database-class/MysqliDb.php(1562): MysqliDb->_buildInsertQuery()\n#2 /var/www/vhosts/[hidden]/httpdocs/vendor/thingengineer/mysqli-database-class/MysqliDb.php(1523): MysqliDb->_buildQuery()\n#3 /var/www/vhosts/[hidden]/httpdocs/vendor/thingengineer/mysqli-database-class/MysqliDb.php(816): MysqliDb->_buildInsert()\n#4 /var/www/vhosts/[hidden]/httpdocs/library/xhr.php(47): MysqliDb->insert()\n#5 {main}\n thrown in /var/www/vhosts/[hidden]/httpdocs/vendor/thingengineer/mysqli-database-class/MysqliDb.php on line 1838', referer: https://www.[hidden]/
```

**Comment by ehylla93** [comment]
Just change the line into: 

`$this->_query .= ' (`' . implode('`, `', $dataColumns) . '`) ';`

**Comment by avbdr** [comment]
fixed in the latest version
